// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: hero_sliders.sql

package database

import (
	"context"
)

const listHeroSliders = `-- name: ListHeroSliders :many
select 
    url,
    image
from
    hero_sliders
order by
    priority desc
`

type ListHeroSlidersRow struct {
	Url   string `json:"url"`
	Image string `json:"image"`
}

func (q *Queries) ListHeroSliders(ctx context.Context) ([]ListHeroSlidersRow, error) {
	rows, err := q.db.Query(ctx, listHeroSliders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeroSlidersRow{}
	for rows.Next() {
		var i ListHeroSlidersRow
		if err := rows.Scan(&i.Url, &i.Image); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
