// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID     int64  `json:"id"`
	Image  string `json:"image"`
	NameFa string `json:"nameFa"`
	NameEn string `json:"nameEn"`
}

type Product struct {
	ID          int64         `json:"id"`
	CategoryID  int64         `json:"categoryId"`
	Images      []string      `json:"images"`
	NameFa      string        `json:"nameFa"`
	NameEn      string        `json:"nameEn"`
	Description string        `json:"description"`
	Attributes  pgtype.Hstore `json:"attributes"`
	Price       int64         `json:"price"`
	PriceOff    *int64        `json:"priceOff"`
	Quantity    int64         `json:"quantity"`
	Discount    *int16        `json:"discount"`
}
